CREATE TABLE `Routes` (
   `Route` int NOT NULL,
   `Name` varchar(125) CHARACTER SET latin1 COLLATE latin1_german1_ci NOT NULL,
   `StartDate` check(`StartDate` <= `EndDate`) date NOT NULL,
   `EndDate` date NOT NULL,
   `LineKey` int NOT NULL,
   `OneWay` char(1) check(`oneWay` in ('Y','N',' ')) DEFAULT 'Y',
   `TrackUsage` check(`TrackUsage` in ('B', 'L', 'R', ' ')) char(1) DEFAULT ' ',
   `CompanyKey` int NOT NULL,
   `tractionType` int NOT NULL,
   `Direction` varchar(6) NOT NULL, 
   `next` int NOT NULL DEFAULt -1,
   `prev` int NOT NULL DEFAULt -1,
   `normalEnter` int NOT NULL DEFAULt 0,
   `normalLeave` int NOT NULL DEFAULt 0,
   `reverseEnter` int NOT NULL DEFAULt 0,
   `reverseLeave` int NOT NULL DEFAULt 0,
   `nextR` int NOT NULL DEFAULt -1,
   `prevR` int NOT NULL DEFAULt -1,
   `Sequence` int NOT NULL DEFAULt -1,
   `ReverseSeq` int NOT NULL DEFAULt -1,
   `lastUpdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`Route`,`Name`,`CompanyKey`,`StartDate`,`EndDate`,`LineKey`),
   KEY `LineKey` (`LineKey`),
   KEY `companyKey` (`CompanyKey`),
   KEY `tractionType` (`tractionType`),
   CONSTRAINT `Routes_ibfk_1` FOREIGN KEY (`LineKey`) REFERENCES `Segments` (`SegmentId`),
   CONSTRAINT `Routes_ibfk_3` FOREIGN KEY (`CompanyKey`) REFERENCES `Companies` (`key`),
   CONSTRAINT `Routes_ibfk_4` FOREIGN KEY (`tractionType`) REFERENCES `TractionTypes` (`tractionType`),
   CONSTRAINT `Routes_ibfk_5` FOREIGN KEY (`Route`) REFERENCES `AltRoute` (`route`)
 ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
