         CREATE TABLE parameters (
          key integer NOT NULL primary key  GENERATED BY DEFAULT AS IDENTITY,
          lat decimal(18,15) NOT NULL default (0),
          lon decimal(18,15) NOT NULL default (0),
          title varchar(50) NOT NULL,
          city varchar(50) NOT NULL,
          minDate date NOT NULL,
          maxDate date NOT NULL,
          alphaRoutes char(1) NOT NULL default ('Y'),
          abbreviationsList VARCHAR(200) NOT NULL DEFAULT '',
          lastUpdate timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP));"; 
