DROP TABLE if exists `Routes`;
CREATE TABLE `Routes` (
             `Route` int(11) NOT NULL,
             `RouteId`  int(11) NOT NULL DEFAULT -1,
             `StartDate`  date NOT NULL,
             `EndDate` date NOT NULL,
             `LineKey` int(11) NOT NULL,
             `OneWay` char(1) check(`oneWay` in ('Y','N',' ')) default ' ' NOT NULL,
             `TrackUsage` text check(`TrackUsage` in ('B', 'L', 'R', ' ')) default ' ' NOT NULL,
             `CompanyKey` int(11) NOT NULL DEFAULT 0,
             `TractionType` int(11) NOT NULL DEFAULT 0,
             `Direction` varchar(6) NOT NULL DEFAULT ' ',
             `Next` int(11) NOT NULL DEFAULT -1,
             `Prev` int(11) NOT NULL DEFAULT -1,
             `NormalEnter` int(11) NOT NULL DEFAULT 0,
             `NormalLeave` int(11) NOT NULL DEFAULT 0,
             `ReverseEnter` int(11) NOT NULL DEFAULT 0,
             `ReverseLeave` int(11) NOT NULL DEFAULT 0,
             `NextR` int(11) NOT NULL DEFAULT -1,
             `PrevR` int(11) NOT NULL DEFAULT -1,
             `Sequence` int(11) NOT NULL DEFAULT -1,
             `ReverseSeq` int(11) NOT NULL DEFAULT -1,
             `LastUpdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
             CONSTRAINT pk PRIMARY key (`Route`,`RouteId`,`CompanyKey`,`StartDate`,`EndDate`,`LineKey`),
             CONSTRAINT `Routes_ibfk_1` FOREIGN KEY (`LineKey`) REFERENCES `Segments` (`SegmentId`) ON UPDATE RESTRICT ON DELETE RESTRICT,
             CONSTRAINT `Routes_ibfk_3` FOREIGN KEY (`CompanyKey`) REFERENCES `Companies` (`key`),
             CONSTRAINT `Routes_ibfk_4` FOREIGN KEY (`tractionType`) REFERENCES `TractionTypes` (`tractionType`),
             CONSTRAINT `Routes_ibfk_5` FOREIGN KEY (`Route`) REFERENCES `AltRoute` (`route`),
             CONSTRAINT `Routes_ibfk_6` FOREIGN KEY (`RouteId`) REFERENCES `RouteName` (`routeId`));
